export const courseList = [
  {
    id: "1",
    title: "React로 시작하는 프론트엔드 입문",
    description: "React 기초부터 실전 프로젝트까지 한 번에!",
    contents:
      "JSX, 컴포넌트, 상태관리, 라우팅 등 프론트엔드의 핵심을 단계별로 학습합니다.",
    thumbnailUrl: "/images/course/react1.jpg",
    instructor: "김코딩",
    category: ["테크", "프로그래밍", "프론트엔드"],
    level: "입문",
    tags: ["프론트엔드", "입문"],
    reviews: [{ rating: 4.8 }],
    studentCount: 320,
    createdAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "2",
    title: "실무에서 바로 쓰는 Figma UI 디자인",
    description: "UI/UX 기초부터 실무 디자인 시스템까지!",
    contents:
      "Figma 툴 활용법, 컴포넌트 설계, UI 패턴, 협업 워크플로우를 배웁니다.",
    thumbnailUrl: "/images/course/figma.jpg",
    instructor: "이디자인",
    category: ["테크", "디자인", "UX/UI 디자인"],
    level: "초급",
    tags: ["UX/UI 디자인", "초급"],
    reviews: [{ rating: 4.7 }],
    studentCount: 150,
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "3",
    title: "Python으로 데이터 분석 시작하기",
    description: "Pandas, Numpy로 배우는 데이터 분석",
    contents: "기초 문법부터 실전 데이터 전처리와 시각화까지 진행합니다.",
    thumbnailUrl: "/images/course/python-data.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "데이터 분석"],
    level: "초급",
    tags: ["데이터 분석", "초급"],
    reviews: [{ rating: 4.6 }],
    studentCount: 210,
    createdAt: "2025-08-20T00:00:00Z",
  },
  {
    id: "4",
    title: "ChatGPT로 업무 자동화하기",
    description: "반복 업무를 AI로 자동화해보세요.",
    contents: "프롬프트 설계, 자동화 워크플로우, Zapier 연동 등을 다룹니다.",
    thumbnailUrl: "/images/course/chatgpt-automation.jpg",
    instructor: "최AI",
    category: ["테크", "AI 스킬업", "ChatGPT"],
    level: "입문",
    tags: ["ChatGPT", "입문"],
    reviews: [{ rating: 4.9 }],
    studentCount: 540,
    createdAt: "2025-07-30T00:00:00Z",
  },
  {
    id: "5",
    title: "기초 드로잉 클래스",
    description: "연필 한 자루로 시작하는 그림의 세계",
    contents: "기초 선 긋기부터 명암 표현, 인물화 기초를 배웁니다.",
    thumbnailUrl: "/images/course/drawing.jpg",
    instructor: "김작가",
    category: ["크리에이티브", "드로잉", "기초 드로잉"],
    level: "입문",
    tags: ["기초 드로잉", "입문"],
    reviews: [{ rating: 4.5 }],
    studentCount: 110,
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "6",
    title: "주식 ETF로 자산 키우기",
    description: "투자 기초부터 ETF 포트폴리오 전략까지",
    contents: "초보 투자자를 위한 ETF 상품 이해와 실전 운용 전략을 배웁니다.",
    thumbnailUrl: "/images/course/etf.jpg",
    instructor: "박투자",
    category: ["커리어", "금융·재테크", "주식·ETF"],
    level: "초급",
    tags: ["주식·ETF", "초급"],
    reviews: [{ rating: 4.3 }],
    studentCount: 400,
    createdAt: "2025-06-12T00:00:00Z",
  },
  {
    id: "7",
    title: "AI를 활용한 마케팅 자동화",
    description: "AI와 함께 SNS 마케팅 효율을 높이기",
    contents: "자동 포스팅, 광고 성과 분석, 고객 세분화를 실습합니다.",
    thumbnailUrl: "/images/course/marketing-ai.jpg",
    instructor: "정마케팅",
    category: ["테크", "마케팅", "디지털 마케팅"],
    level: "중급",
    tags: ["디지털 마케팅", "중급"],
    reviews: [{ rating: 4.4 }],
    studentCount: 180,
    createdAt: "2025-05-10T00:00:00Z",
  },
  {
    id: "8",
    title: "웹 백엔드 입문: Node.js로 시작하기",
    description: "서버 기초와 REST API 설계 실습",
    contents: "Node.js와 Express를 이용해 간단한 API 서버를 만들어봅니다.",
    thumbnailUrl: "/images/course/node-backend.jpg",
    instructor: "박백엔드",
    category: ["테크", "프로그래밍", "백엔드"],
    level: "입문",
    tags: ["백엔드", "입문"],
    reviews: [{ rating: 4.8 }],
    studentCount: 260,
    createdAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "9",
    title: "스페인어 회화 마스터",
    description: "여행에서 바로 쓸 수 있는 스페인어 표현",
    contents: "기초 문법, 발음, 일상 회화를 상황별로 배웁니다.",
    thumbnailUrl: "/images/course/spanish.jpg",
    instructor: "로사",
    category: ["언어", "제2 외국어", "스페인어"],
    level: "입문",
    tags: ["스페인어", "입문"],
    reviews: [{ rating: 4.7 }],
    studentCount: 330,
    createdAt: "2025-09-10T00:00:00Z",
  },
  {
    id: "10",
    title: "토익 900+ 목표 달성 비법",
    description: "단기간 점수 상승을 위한 실전 전략",
    contents: "LC/RC 집중 공략, 파트별 공략법, 기출문제 분석",
    thumbnailUrl: "/images/course/toeic.jpg",
    instructor: "토익쌤",
    category: ["언어", "외국어 시험", "토익"],
    level: "중급",
    tags: ["토익", "중급"],
    reviews: [{ rating: 4.6 }],
    studentCount: 420,
    createdAt: "2025-08-25T00:00:00Z",
  },
  {
    id: "11",
    title: "모바일 앱 개발 실전: React Native",
    description: "단 하나의 코드로 iOS/Android 동시 개발",
    contents: "React Native를 활용한 앱 제작, 배포까지 실습합니다.",
    thumbnailUrl: "/images/course/react-native.jpg",
    instructor: "한풀스택",
    category: ["테크", "프로그래밍", "모바일 앱"],
    level: "중급",
    tags: ["모바일 앱", "중급"],
    reviews: [{ rating: 4.9 }],
    studentCount: 370,
    createdAt: "2025-09-05T00:00:00Z",
  },
];
